name: 'Add issues to fixVersion'
description: 'Adds issues to version in Jira'
inputs:
  versionName:
    description: 'Name of the version to create'
    required: true
  projectKey:
    description: 'Jira project key'
    required: true
  jiraUser:
    description: 'Jira user email'
    required: true
  jiraToken:
    description: 'Jira API token'
    required: true
  jiraUrl:
    description: 'Jira instance URL'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PR_TITLE:  ${{ inputs.prTitle }} #${{ github.event.pull_request.title }}
    FIX_VERSION: ${{ inputs.versionName }}
    PROJECT_KEY: ${{ inputs.projectKey }}
    JIRA_USER: ${{ inputs.jiraUser }}
    JIRA_TOKEN: ${{ inputs.jiraToken }}
    JIRA_URL: ${{ inputs.jiraUrl }}
