name: Jira Release Action

on:
  create:
    branches:
      - 'release/*'

jobs:
  jira-release:
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
        id: extract_branch

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Jira Release Action
        uses: allwhere/allwhere-github-actions/jira-release-creator@v1.0
        with:
          versionName: ${{ env.BRANCH_NAME }}
          projectKey: DEV
          jiraUser: ${{ secrets.JIRA_AUTOMATION_USER }}
          jiraToken: ${{ secrets.JIRA_AUTOMATION_TOKEN }}
          jiraUrl: https://allwhere.atlassian.net
